#!/usr/local/bin/php
<?php

// Load library and own dependencies
require '/opt/vendor/autoload.php';

use ElephpantLambda\Config\EnvReader;
use ElephpantLambda\Config\Store as ConfigStore;
use ElephpantLambda\TaskLoader;
use ElephpantLambda\RunLoop;
use GuzzleHttp\Client;

// Read config from env vars
$envReader = new EnvReader();
$config = $envReader->run($_ENV, new ConfigStore());
$runtimeHost = $config->getLambdaRuntimeApi();

// Load the function specified by the CMD
$loader = new TaskLoader($config->getTaskPath());
$taskName = $config->getTaskName();
$loader->load($taskName);

// Mediator loop
$runLoop = new RunLoop(new Client(), $runtimeHost, $taskName);
$runLoop->runLoop();
